In [1]:
%load_ext sql

In [2]:
import csv, sqlite3, prettytable

prettytable.DEFAULT = 'DEFAULT'

In [17]:
con = sqlite3.connect("SC_Tdb.db")
cor = con.cursor()

In [4]:
%sql sqlite:///SC_Tdb.db

In [67]:
import pandas as pd
import os

filepath = os.path.join(os.getcwd().split('backend')[0],"e-GMAT_SalesCall_DataAnalysis_80")
filepath

'C:\\GOWDATA\\PROJECTS\\e-GMAT-SalesCall-Analysis\\e-GMAT_SalesCall_DataAnalysis_80'

In [68]:
df_data = pd.read_csv(os.path.join(filepath, "combined_dataset_80.csv"))
df_data.head(2)

,transcript_id,month,conversion_likelihood,reasoning,emotions_detected,location,education,organization,date,agent_emotions_with_score,agent_duration,agent_keywords,prospect_emotions_with_score,prospect_duration,prospect_keywords,start_end_time,agent_vs_prospect_num
0,100_20250213,Feb,0.7,Prospect showed positive emotions (more than 2...,"approval,gratitude,optimism,admiration,optimis...",India,"b.tech, engineering","UPSC, GMAT, GP, Indian School of Business, CAT...","2021, 11 months, 7 to 8 months","Introduction: admiration - 0.72, curiosity - 0...",Introduction: 21\nProspect’s performance: 107\...,"Introduction: GMAT Club, India, GMAT, MAT, Cor...","Introduction: realization - 0.82, neutral - 0....",Introduction: 21\nProspect’s performance: 20\n...,"Introduction: Electronics and Communication, e...",Introduction: 00:00:02 - 00:04:02\nProspect’s ...,Introduction: 1\nProspect’s performance: 5\nAg...
1,101_20250212,Feb,0.8,Prospect showed positive emotion (hope or conf...,"gratitude,optimism,optimism,optimism,realizati...",No Info,"engineering, masters","PMS, GMAC, CFA L1",about 1 1/2 years,Introduction: admiration - 1.0\nProspect’s per...,Introduction: 22\nProspect’s performance: 93\n...,"Introduction: plans with GMAT, GMAT, Awesome, ...",Introduction: desire - 0.8\nProspect’s perform...,Introduction: 20\nProspect’s performance: 31\n...,"Introduction: engineer by profession, basicall...",Introduction: 00:00:02 - 00:02:39\nProspect’s ...,Introduction: 1\nProspect’s performance: 3\nAg...

In [69]:
df_data.to_sql("transcripts", con, if_exists="replace", index=False, method="multi")

142

In [70]:
%sql drop table if exists sct_insights

 * sqlite:///SC_Tdb.db
Done.

[]

In [71]:
%sql create table sct_insights as select * from transcripts

 * sqlite:///SC_Tdb.db
Done.

[]

In [72]:
%sql select * from sct_insights limit 1

 * sqlite:///SC_Tdb.db
Done.

[('100_20250213', 'Feb', 0.7, 'Prospect showed positive emotions (more than 2) during wrap-up/Q&A, Either prospect showed willingness and curiosity in performance/targets discussio ... (43 characters truncated) ... ng price discussion, Agent maintained high confidence or relief near end, Agent catered to the prospect needs with clarity during product explanation', 'approval,gratitude,optimism,admiration,optimism,realization,optimism', 'India', 'b.tech, engineering', 'UPSC, GMAT, GP, Indian School of Business, CAT, B.Tech, EG Mat, Electronics and Communication, Manhattan Review, PwC India', '2021, 11 months, 7 to 8 months', 'Introduction: admiration - 0.72, curiosity - 0.97\nProspect’s performance: approval - 0.46, curiosity - 0.32\nAgent drawing up plan: neutral - 0.99\n ... (36 characters truncated) ... 38\nPrice discussion: caring - 0.39, optimism - 0.65, neutral - 0.33\nQ&A: approval - 0.98\nWrap: admiration - 0.74, approval - 0.94, optimism - 0.81', 'Introduction: 21\nProspect’s performance: 107\nAgent drawing up plan: 161\nExplaining product: 271\nPrice discussion: 68\nQ&A: 56\nWrap: 26', 'Introduction: GMAT Club, India, GMAT, MAT, Correct, IIMA and IIMC, familiar, Club\nProspect’s performance: GMAT, yeah, planner, mock, good, verbal, m ... (387 characters truncated) ... iling, absolutely, happen\nWrap: admission consultants, professional consultants, consultants, Mat will eventually, GMAT, yeah, things happen, Indian', 'Introduction: realization - 0.82, neutral - 0.94\nProspect’s performance: neutral - 1.0\nAgent drawing up plan: admiration - 0.95, curiosity - 0.49,  ... (106 characters truncated) ...  approval - 0.41, curiosity - 0.92, optimism - 0.9\nQ&A: approval - 0.38, curiosity - 0.52\nWrap: admiration - 0.51, gratitude - 1.0, optimism - 0.48', 'Introduction: 21\nProspect’s performance: 20\nAgent drawing up plan: 8\nExplaining product: 25\nPrice discussion: 17\nQ&A: 29\nWrap: 16', 'Introduction: Electronics and Communication, engineering in Electronics, completed my B.Tech, B.Tech engineering, joined PwC India, CAT, year July, s ... (408 characters truncated) ... months\nQ&A: IIMA and IIMC, year MBA, Yeah, MBA, good, India, year, IIMA\nWrap: yeah, MAT, Bye, institute in India, provided, score, India, Sumanthir', 'Introduction: 00:00:02 - 00:04:02\nProspect’s performance: 00:04:16 - 00:15:26\nAgent drawing up plan: 00:15:29 - 00:32:19\nExplaining product: 00:32:24 - 01:00:46\nPrice discussion: 01:00:52 - 01:08:05\nQ&A: 01:08:12 - 01:14:54\nWrap: 01:15:04 - 01:17:17', 'Introduction: 1\nProspect’s performance: 5\nAgent drawing up plan: 20\nExplaining product: 10\nPrice discussion: 4\nQ&A: 1\nWrap: 1')]

In [55]:
%sql create view overview as select transcript_id,month,conversion_likelihood,reasoning from sct_insights

 * sqlite:///SC_Tdb.db
(sqlite3.OperationalError) view overview already exists
[SQL: create view overview as select transcript_id,month,conversion_likelihood,reasoning from sct_insights]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [73]:
%sql select * from overview limit 3

 * sqlite:///SC_Tdb.db
Done.

[('100_20250213', 'Feb', 0.7, 'Prospect showed positive emotions (more than 2) during wrap-up/Q&A, Either prospect showed willingness and curiosity in performance/targets discussio ... (43 characters truncated) ... ng price discussion, Agent maintained high confidence or relief near end, Agent catered to the prospect needs with clarity during product explanation'),
 ('101_20250212', 'Feb', 0.8, 'Prospect showed positive emotion (hope or confidence or etc.) during wrap-up/Q&A, Prospect showed willingness and curiosity in performance/targets di ... (187 characters truncated) ... ng price discussion, Agent maintained high confidence or relief near end, Agent catered to the prospect needs with clarity during product explanation'),
 ('102_20250212', 'Feb', 0.7, 'Prospect showed positive emotions (more than 2) during wrap-up/Q&A, Either prospect showed willingness and curiosity in performance/targets discussio ... (43 characters truncated) ... ng price discussion, Agent maintained high confidence or relief near end, Agent catered to the prospect needs with clarity during product explanation')]

In [74]:
%sql SELECT * FROM overview WHERE LOWER(transcript_id) LIKE LOWER('%100%')

 * sqlite:///SC_Tdb.db
Done.

[('100_20250213', 'Feb', 0.7, 'Prospect showed positive emotions (more than 2) during wrap-up/Q&A, Either prospect showed willingness and curiosity in performance/targets discussio ... (43 characters truncated) ... ng price discussion, Agent maintained high confidence or relief near end, Agent catered to the prospect needs with clarity during product explanation')]

In [75]:
%sql SELECT transcript_id, location, education, organization FROM sct_insights WHERE conversion_likelihood < '1.55'

 * sqlite:///SC_Tdb.db
Done.

[('100_20250213', 'India', 'b.tech, engineering', 'UPSC, GMAT, GP, Indian School of Business, CAT, B.Tech, EG Mat, Electronics and Communication, Manhattan Review, PwC India'),
 ('101_20250212', 'No Info', 'engineering, masters', 'PMS, GMAC, CFA L1'),
 ('102_20250212', 'No Info', 'No Info', 'GMAT'),
 ('103_20250212', 'Milan, Rome, US', 'No Info', 'Business School, GMAT, G Mac, IELTS'),
 ('104_20250212', 'No Info', 'No Info', 'WhatsApp'),
 ('105_20250215', 'No Info', 'No Info', 'IIM'),
 ('106_20250215', 'No Info', 'No Info', 'No Info'),
 ('107_20250215', 'No Info', 'No Info', 'No Info'),
 ('108_20250216', 'No Info', 'No Info', 'No Info'),
 ('109_20250216', 'Europe', 'No Info', 'Co Institute of Management, GMAT, HCL Tech'),
 ('10_20250107', 'No Info', 'No Info', 'No Info'),
 ('110_20250216', 'No Info', 'No Info', 'No Info'),
 ('111_20250216', 'No Info', 'No Info', 'CAT'),
 ('112_20250213', 'No Info', 'No Info', 'Mercy R&D'),
 ('113_20250217', 'No Info', 'No Info', 'No Info'),
 ('114_20250214', 'No Info', 'No Info', 'No Info'),
 ('115_20250214', 'UK', 'No Info', 'No Info'),
 ('116_20250217', 'Paris, India, US', 'diploma', 'CIA, GMAT, INR, CAT, MBBS, ILDS, NMAT'),
 ('117_20250217', 'No Info', 'No Info', 'GMAT, High Radius Technologies, Google, Deloitte, the High Radius Technologies'),
 ('118_20250217', 'No Info', 'No Info', 'No Info'),
 ('119_20250217', 'No Info', 'No Info', 'GMAT'),
 ('11_20250107', 'No Info', 'No Info', 'No Info'),
 ('120_20250218', 'Switzerland', 'No Info', 'the University of Saint Gown, GMAT, GMAC'),
 ('121_20250218', 'UK', 'commerce, bachelors, arts', 'TTP, GMAC, Delhi College of Arts and Commerce'),
 ('122_20250219', 'Frankfurt, Germany', 'No Info', 'Namura, GMAT, Nomura, Morgan Sandy'),
 ('123_20250219', 'No Info', 'No Info', 'SOP'),
 ('124_20250219', 'India', 'No Info', 'No Info'),
 ('125_20250221', 'No Info', 'engineering', 'No Info'),
 ('126_20250221', 'No Info', 'No Info', 'No Info'),
 ('127_20250222', 'No Info', 'No Info', 'Amrit'),
 ('128_20250223', 'No Info', 'No Info', 'No Info'),
 ('129_20250223', 'No Info', 'bachelor, engineering', 'Warton, CBS, NYU, London Business School, GRE'),
 ('12_20250107', 'No Info', 'No Info', 'No Info'),
 ('130_20250219', 'No Info', 'No Info', 'EG MAT'),
 ('131_20250224', 'No Info', 'No Info', 'No Info'),
 ('132_20250224', 'No Info', 'No Info', 'GMAT, Piyush'),
 ('133_20250225', 'No Info', 'No Info', 'CAD, GMAT'),
 ('134_20250226', 'Mumbai', 'phd', 'Army'),
 ('135_20250226', 'No Info', 'No Info', 'NMS Mumbai, SPJ, GMAT'),
 ('136_20250226', 'No Info', 'graduate', 'No Info'),
 ('137_20250227', 'MMS Mumbai', 'science, computer science', 'DI, the Hammond Connected Services'),
 ('138_20250226', 'Pune, New York', 'bachelor, engineering', 'GMAT, EG MAT, SC, PGPX, PMO, SCSC'),
 ('139_20250227', 'No Info', 'masters', 'YouTube, Google'),
 ('13_20250108', 'America, Stanford', 'engineering', 'GMAT'),
 ('140_20250227', 'No Info', 'No Info', 'No Info'),
 ('141_20250228', 'No Info', 'No Info', 'WhatsApp'),
 ('142_20250224', 'No Info', 'high school', 'GMAT'),
 ('14_20250110', 'No Info', 'No Info', 'No Info'),
 ('15_20250110', 'No Info', 'No Info', 'Hello Nithya'),
 ('16_20250110', 'India', 'No Info', 'CAT, GMAT, ISP'),
 ('17_20250110', 'India, US', 'No Info', 'GMAT, TTP, CAT, EG Mat, SAT, ISP Hyderabad'),
 ('18_20250111', 'No Info', 'No Info', 'No Info'),
 ('19_20250112', 'Bihar, Kerala, Orissa', 'No Info', 'No Info'),
 ('1_20250101', 'No Info', 'No Info', 'Amrit'),
 ('20_20250112', 'No Info', 'No Info', 'NMS Mumbai, GMAT, CAT, OG, JP Institute in Electronics, GMAC, Deloitte, Bosdart'),
 ('21_20250112', 'No Info', 'No Info', 'No Info'),
 ('22_20250112', 'No Info', 'No Info', 'GMAT'),
 ('23_20250112', 'Sweden, Mumbai, India Amadora, US, USA, Chicago, India', 'No Info', 'che, GMAT, NBA, BBA, MATLAB, Chicago University TK'),
 ('24_20250111', 'No Info', 'No Info', 'No Info'),
 ('25_20250110', 'No Info', 'No Info', 'No Info'),
 ('26_20250113', 'No Info', 'No Info', 'EG, GMAT, Hyderabad'),
 ('27_20250110', 'Kanpur', 'bachelor, engineering', 'No Info'),
 ('28_20250113', 'Kalyan', 'bachelors', 'GMAT, YouTube, EG MAT, Birla College, BMS Bachelors of Management Studies'),
 ('29_20250113', 'Mumbai', 'No Info', 'GMAT, NS YSR, SYBMS, University of Memphis'),
 ('2_20250102', 'No Info', 'No Info', 'GMAT, GMAC'),
 ('30_20250114', 'No Info', 'No Info', 'No Info'),
 ('31_20250113', 'No Info', 'No Info', 'GMAT'),
 ('32_20250113', 'Hyderabad, Mumbai, US, Canada, Delhi, India', 'No Info', 'The Pacific, Hyderabad'),
 ('33_20250114', 'Mumbai', 'No Info', 'CAD, GMAT, CAT, EG, GMAC, Christ University'),
 ('34_20250114', 'No Info', 'No Info', 'No Info'),
 ('35_20250115', 'US', 'No Info', 'GMAT'),
 ('36_20250114', 'No Info', 'No Info', 'No Info'),
 ('37_20250115', 'No Info', 'No Info', 'No Info'),
 ('38_20250115', 'Jaipur', 'bachelor', 'UP'),
 ('39_20250116', 'No Info', 'No Info', 'Amrit, GMAT'),
 ('3_20250102', 'No Info', 'engineering, masters', 'Budweiser'),
 ('40_20250116', 'Ghaziabad', 'No Info', 'Vikram'),
 ('41_20250117', 'No Info', 'No Info', 'CRD'),
 ('42_20250119', 'Amruthai', 'No Info', 'GMAT'),
 ('43_20250119', 'No Info', 'No Info', 'CAT, GMAT, IIM'),
 ('44_20250119', 'Chhattisgarh, Gurgaon', 'science, engineering', 'CAT, BBA, Pan India B&M, Urban Company, BBM, NPS, Apollo, Tata, Chhattisgarh, UP'),
 ('45_20250119', 'No Info', 'No Info', 'GMAT'),
 ('46_20250117', 'No Info', 'No Info', 'No Info'),
 ('47_20250120', 'No Info', 'No Info', 'No Info'),
 ('48_20250120', 'No Info', 'No Info', 'No Info'),
 ('49_20250116', 'India', 'No Info', 'BILR, GMAT, ISP, NMAT'),
 ('4_20250103', 'India, Mumbai, Ahmedabad', 'No Info', 'CAT, DevOps, GMAT, PGPX'),
 ('50_20250121', 'No Info', 'No Info', 'GMAT, WhatsApp, ISB Hyderabad, CAT, Data, GRE, Australia National Australia Bank'),
 ('51_20250121', 'No Info', 'science, bachelor, computer science, masters', 'Business School, NBA'),
 ('52_20250121', 'No Info', 'No Info', 'No Info'),
 ('53_20250122', 'No Info', 'No Info', 'No Info'),
 ('54_20250122', 'No Info', 'No Info', 'No Info'),
 ('55_20250122', 'No Info', 'No Info', 'No Info'),
 ('56_20250121', 'No Info', 'No Info', 'No Info'),
 ('57_20250122', 'India', 'No Info', 'GMAT, CAT, MSR, DI, Data'),
 ('58_20250120', 'No Info', 'bachelor', 'NMS, Chitkala University, GMAT'),
 ('59_20250121', 'No Info', 'No Info', 'Google'),
 ('5_20250104', 'No Info', 'No Info', 'No Info'),
 ('60_20250124', 'No Info', 'No Info', 'No Info'),
 ('61_20250124', 'No Info', 'No Info', 'GMAT, Tiga Tiga'),
 ('62_20250124', 'Delhi, Bangalore', 'No Info', 'No Info'),
 ('63_20250127', 'No Info', 'No Info', 'GMAT, gmatclub.com'),
 ('64_20250127', 'No Info', 'science, computer science', 'GMAT'),
 ('65_20250127', 'No Info', 'No Info', 'CAD, NBA, Google'),
 ('66_20250128', 'No Info', 'No Info', 'GMAT, BBA'),
 ('67_20250128', 'No Info', 'No Info', 'CAT, GMAT, AMD, BC'),
 ('68_20250129', 'India, California', 'commerce, arts', 'Badruka College of Commerce, Badruka Commerce'),
 ('69_20250130', 'No Info', 'No Info', 'No Info'),
 ('6_20250104', 'No Info', 'No Info', 'No Info'),
 ('70_20250131', 'No Info', 'b.tech', 'B.Tech, NGP, GMAC, Deloitte'),
 ('71_20250129', 'No Info', 'No Info', 'PGP, ISP, PDF'),
 ('72_20250129', 'No Info', 'No Info', 'CAT, GMAT, Focus edition'),
 ('73_20250130', 'Kenya', 'No Info', 'G Mart, GRE'),
 ('74_20250202', 'US', 'No Info', 'Deloitte USA, GMAT, Workx, ISP, ABC'),
 ('75_20250202', 'No Info', 'No Info', 'No Info'),
 ('76_20250202', 'No Info', 'bcom', 'Bcom, ENY'),
 ('77_20250203', 'No Info', 'No Info', 'WhatsApp, Harvard, MBA'),
 ('78_20250204', 'No Info', 'No Info', 'No Info'),
 ('79_20250204', 'No Info', 'No Info', 'No Info'),
 ('7_20250105', 'India', 'No Info', 'NMS Mumbai, GMAT, CAT, Thomson Reuters'),
 ('80_20250204', 'No Info', 'No Info', 'No Info'),
 ('81_20250205', 'No Info', 'No Info', 'GMAT, CAT, GMART, Hansraj College, United Airlines'),
 ('82_20250205', 'India', 'No Info', 'GMAT, GMAC'),
 ('83_20250205', 'No Info', 'No Info', 'CAT, Lucknow Pradesh'),
 ('84_20250206', 'India', 'No Info', 'EG Mat, EG'),
 ('85_20250206', 'Mumbai', 'No Info', 'Thane Mulund'),
 ('86_20250207', 'No Info', 'No Info', 'GMAT, AG'),
 ('87_20250207', 'No Info', 'No Info', 'No Info'),
 ('88_20250207', 'No Info', 'No Info', 'No Info'),
 ('89_20250208', 'No Info', 'No Info', 'No Info'),
 ('8_20250105', 'India', 'No Info', 'CAT, GMAT, MVA'),
 ('90_20250208', 'No Info', 'No Info', 'No Info'),
 ('91_20250208', 'No Info', 'No Info', 'No Info'),
 ('92_20250208', 'No Info', 'No Info', 'No Info'),
 ('93_20250210', 'No Info', 'No Info', 'No Info'),
 ('94_20250210', 'No Info', 'No Info', 'No Info'),
 ('95_20250211', 'No Info', 'engineering', 'GMAT'),
 ('96_20250211', 'No Info', 'No Info', 'GMAT'),
 ('97_20250212', 'No Info', 'science, bachelor, computer science', 'CAT, CAD, XLRI, GMAT'),
 ('98_20250212', 'No Info', 'No Info', 'No Info'),
 ('99_20250211', 'No Info', 'No Info', 'No Info'),
 ('9_20250106', 'Mumbai', 'engineering', 'GMAT')]

In [76]:
%sql select count(*) as 'conversion_likelihood>0.55' from overview where conversion_likelihood > '0.55'

 * sqlite:///SC_Tdb.db
Done.

[(70,)]

In [77]:
%sql select count(*) as 'conversion_likelihood>=0.8' from overview where conversion_likelihood >= '0.8'

 * sqlite:///SC_Tdb.db
Done.

[(15,)]

In [78]:
%sql select count(*) as 'conversion_likelihood<0.55' from overview where conversion_likelihood < '0.55'

 * sqlite:///SC_Tdb.db
Done.

[(72,)]

In [79]:
%sql select count(*) as 'conversion_likelihood<0.4' from overview where conversion_likelihood < '0.4'

 * sqlite:///SC_Tdb.db
Done.

[(19,)]